Resources:
  DealerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableDealer}
      AttributeDefinitions:
        - AttributeName: dealership
          AttributeType: S
        - AttributeName: dealerId
          AttributeType: S
      KeySchema:
        - AttributeName: dealership
          KeyType: HASH
        - AttributeName: dealerId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST